export const cakes = [
    {
        id: 1,
        name: 'Chocolate Truffle Cake',
        description: 'Indulge in the richness of our Chocolate Truffle Cake, featuring layers of velvety chocolate sponge infused with a decadent truffle filling. Each bite delivers an intense chocolate experience, with a smooth and creamy texture that melts in your mouth. Perfect for chocolate lovers seeking a luxurious treat that combines rich flavors with an elegant presentation.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.5,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 349,
                discountedPrice: 309,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 459,
                discountedPrice: 429,
            },
        ],
    },
    {
        id: 2,
        name: 'Vanilla Bean Cake',
        description: 'Savor the delicate flavors of our Vanilla Bean Cake, made with real vanilla beans and a light, fluffy sponge. Perfectly layered with creamy vanilla frosting, this cake offers a sweet and aromatic taste that is both comforting and satisfying.',
        image: '../assets/cake.jpeg',
        subCategory: 'Veg',
        starRating: 4.3,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 299,
                discountedPrice: 279,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 399,
                discountedPrice: 369,
            },
        ],
    },
    {
        id: 3,
        name: 'Red Velvet Cake',
        description: 'Experience the allure of our Red Velvet Cake, featuring a rich red sponge layered with luscious cream cheese frosting. With its velvety texture and subtle cocoa flavor, this cake offers a striking and memorable dessert option.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.6,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 369,
                discountedPrice: 339,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 499,
                discountedPrice: 459,
            },
        ],
    },
    {
        id: 4,
        name: 'Lemon Drizzle Cake',
        description: 'Delight in the zesty flavor of our Lemon Drizzle Cake, with a tangy lemon sponge topped with a sweet lemon glaze. This cake offers a refreshing and vibrant taste that is perfect for a light and uplifting dessert.',
        image: '../assets/cake.jpeg',
        subCategory: 'Veg',
        starRating: 4.4,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 329,
                discountedPrice: 299,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 429,
                discountedPrice: 399,
            },
        ],
    },
    {
        id: 5,
        name: 'Carrot Cake',
        description: 'Enjoy the wholesome flavors of our Carrot Cake, with finely grated carrots and a hint of spice, topped with rich cream cheese frosting. This cake combines a moist texture with a sweet and spicy flavor profile.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.5,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 359,
                discountedPrice: 329,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 469,
                discountedPrice: 429,
            },
        ],
    },
    {
        id: 6,
        name: 'Strawberry Shortcake',
        description: 'Delight in the fruity goodness of our Strawberry Shortcake, with layers of light sponge cake, fresh strawberries, and whipped cream. This dessert offers a perfect balance of sweetness and tartness.',
        image: '../assets/cake.jpeg',
        subCategory: 'Veg',
        starRating: 4.7,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 339,
                discountedPrice: 309,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 439,
                discountedPrice: 409,
            },
        ],
    },
    {
        id: 7,
        name: 'Coffee Walnut Cake',
        description: 'Savor the rich flavor of our Coffee Walnut Cake, with a blend of freshly brewed coffee and crunchy walnuts. This cake offers a bold coffee taste complemented by the nutty crunch of walnuts.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.6,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 369,
                discountedPrice: 339,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 479,
                discountedPrice: 439,
            },
        ],
    },
    {
        id: 8,
        name: 'Pineapple Upside-Down Cake',
        description: 'Enjoy the tropical flavor of our Pineapple Upside-Down Cake, with caramelized pineapples and a soft, moist sponge cake. This dessert is a delightful combination of sweet and tangy flavors.',
        image: '../assets/cake.jpeg',
        subCategory: 'Veg',
        starRating: 4.4,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 319,
                discountedPrice: 289,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 419,
                discountedPrice: 389,
            },
        ],
    },
    {
        id: 9,
        name: 'Mango Mousse Cake',
        description: 'Experience the tropical delight of our Mango Mousse Cake, with a light and airy mousse made from fresh mangoes. This cake offers a smooth and refreshing flavor that’s perfect for a summer treat.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.8,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 349,
                discountedPrice: 319,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 459,
                discountedPrice: 429,
            },
        ],
    },
    {
        id: 10,
        name: 'Chocolate Lava Cake',
        description: 'Indulge in our Chocolate Lava Cake, with a gooey molten center of rich chocolate encased in a soft and fudgy sponge. Each bite delivers a burst of warm chocolate that’s simply irresistible.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.9,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 389,
                discountedPrice: 359,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 499,
                discountedPrice: 469,
            },
        ],
    },
    {
        id: 11,
        name: 'Almond Cake',
        description: 'Relish the nutty flavor of our Almond Cake, with finely chopped almonds mixed into a light sponge and topped with a smooth almond frosting. This cake offers a satisfying crunch and a rich almond taste.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.5,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 379,
                discountedPrice: 349,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 489,
                discountedPrice: 459,
            },
        ],
    },
    {
        id: 12,
        name: 'Raspberry Cheesecake',
        description: 'Enjoy the creamy richness of our Raspberry Cheesecake, with a graham cracker crust and a topping of fresh raspberries. This cheesecake offers a perfect balance of sweet and tart flavors with a creamy texture.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.7,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 399,
                discountedPrice: 369,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 509,
                discountedPrice: 479,
            },
        ],
    },
    {
        id: 13,
        name: 'Hazelnut Cake',
        description: 'Treat yourself to our Hazelnut Cake, featuring layers of hazelnut-infused sponge and a rich hazelnut cream filling. This cake offers a delightful nutty flavor and a smooth, creamy texture.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.6,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 379,
                discountedPrice: 349,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 489,
                discountedPrice: 459,
            },
        ],
    },
    {
        id: 14,
        name: 'Matcha Green Tea Cake',
        description: 'Experience the unique flavor of our Matcha Green Tea Cake, with a light sponge infused with premium matcha green tea powder. This cake offers a subtle, earthy taste with a smooth and delicate texture.',
        image: '../assets/cake.jpeg',
        subCategory: 'Veg',
        starRating: 4.4,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 349,
                discountedPrice: 319,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 459,
                discountedPrice: 429,
            },
        ],
    },
    {
        id: 15,
        name: 'Black Forest Cake',
        description: 'Enjoy the classic flavors of our Black Forest Cake, with layers of chocolate sponge, whipped cream, and cherries. This cake combines rich chocolate with a fruity twist for a deliciously indulgent treat.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.7,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 359,
                discountedPrice: 329,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 469,
                discountedPrice: 439,
            },
        ],
    },
    {
        id: 16,
        name: 'Tiramisu Cake',
        description: 'Indulge in the layers of our Tiramisu Cake, featuring coffee-soaked sponge and a rich mascarpone cream. This cake offers a blend of bold coffee flavor and creamy sweetness for a classic Italian dessert experience.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.8,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 389,
                discountedPrice: 359,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 499,
                discountedPrice: 469,
            },
        ],
    },
    {
        id: 17,
        name: 'Coconut Cake',
        description: 'Enjoy the tropical flavors of our Coconut Cake, with a moist coconut sponge and a creamy coconut frosting. This cake offers a sweet and nutty flavor that transports you to a sunny paradise.',
        image: '../assets/cake.jpeg',
        subCategory: 'Veg',
        starRating: 4.5,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 359,
                discountedPrice: 329,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 469,
                discountedPrice: 439,
            },
        ],
    },
    {
        id: 18,
        name: 'Pistachio Cake',
        description: 'Savor the unique flavor of our Pistachio Cake, with finely ground pistachios mixed into a light sponge and topped with a smooth pistachio frosting. This cake offers a rich and nutty taste with a luxurious texture.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.6,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 379,
                discountedPrice: 349,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 489,
                discountedPrice: 459,
            },
        ],
    },
    {
        id: 19,
        name: 'Pumpkin Spice Cake',
        description: 'Delight in the seasonal flavors of our Pumpkin Spice Cake, with a moist sponge infused with pumpkin puree and warming spices. This cake is topped with a creamy frosting for a comforting and flavorful treat.',
        image: '../assets/cake.jpeg',
        subCategory: 'Veg',
        starRating: 4.4,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 329,
                discountedPrice: 299,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 429,
                discountedPrice: 399,
            },
        ],
    },
    {
        id: 20,
        name: 'Cinnamon Roll Cake',
        description: 'Enjoy the warm and comforting flavors of our Cinnamon Roll Cake, with layers of cinnamon-infused sponge and a creamy frosting. This cake offers a sweet and spicy taste that is perfect for any occasion.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.6,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 359,
                discountedPrice: 329,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 469,
                discountedPrice: 439,
            },
        ],
    },
];
