export const cakes = [
    {
        id: 1,
        name: 'Chocolate Truffle Cake',
        price: '549',
        description: 'Rich and creamy chocolate cake with layers of truffle.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.5,
    },
    {
        id: 2,
        name: 'Red Velvet Cake',
        price: '699',
        description: 'Delicious red velvet cake with cream cheese frosting.',
        image: '../assets/cake.jpeg',
        subCategory: 'veg',
        starRating: 4.7,
    },
    {
        id: 3,
        name: 'Black Forest Cake',
        price: '599',
        description: 'Classic black forest cake with layers of chocolate and cherries.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.3,
    },
    {
        id: 4,
        name: 'Pineapple Cake',
        price: '499',
        description: 'Light and refreshing pineapple flavored cake.',
        image: '../assets/cake.jpeg',
        subCategory: 'veg',
        starRating: 4.0,
    },
    {
        id: 5,
        name: 'Butterscotch Cake',
        price: '549',
        description: 'Delicious butterscotch cake with caramel drizzle.',
        image: '../assets/cake.jpeg',
        subCategory: 'veg',
        starRating: 4.2,
    },
    {
        id: 6,
        name: 'Fruit Cake',
        price: '749',
        description: 'Fresh fruit cake with layers of seasonal fruits.',
        image: '../assets/cake.jpeg',
        subCategory: 'veg',
        starRating: 4.6,
    },
    {
        id: 7,
        name: 'Vanilla Cake',
        price: '499',
        description: 'Classic vanilla cake with buttercream frosting.',
        image: '../assets/cake.jpeg',
        subCategory: 'veg',
        starRating: 4.1,
    },
    {
        id: 8,
        name: 'Mango Cake',
        price: '599',
        description: 'Delicious mango flavored cake with fresh mango slices.',
        image: '../assets/cake.jpeg',
        subCategory: 'veg',
        starRating: 4.4,
    },
    {
        id: 9,
        name: 'Coffee Cake',
        price: '649',
        description: 'Rich coffee flavored cake with a mocha frosting.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.5,
    },
    {
        id: 10,
        name: 'Strawberry Cake',
        price: '599',
        description: 'Sweet strawberry cake with fresh strawberry topping.',
        image: '../assets/cake.jpeg',
        subCategory: 'veg',
        starRating: 4.3,
    },
    {
        id: 11,
        name: 'Lemon Cake',
        price: '549',
        description: 'Tangy lemon cake with a zesty lemon glaze.',
        image: '../assets/cake.jpeg',
        subCategory: 'veg',
        starRating: 4.2,
    },
    {
        id: 12,
        name: 'Blueberry Cake',
        price: '699',
        description: 'Delicious blueberry cake with fresh blueberries.',
        image: '../assets/cake.jpeg',
        subCategory: 'veg',
        starRating: 4.6,
    },
    {
        id: 13,
        name: 'Carrot Cake',
        price: '649',
        description: 'Moist carrot cake with cream cheese frosting.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.4,
    },
    {
        id: 14,
        name: 'Banana Cake',
        price: '549',
        description: 'Sweet banana cake with a caramel glaze.',
        image: '../assets/cake.jpeg',
        subCategory: 'veg',
        starRating: 4.3,
    },
    {
        id: 15,
        name: 'Coconut Cake',
        price: '599',
        description: 'Tropical coconut cake with coconut flakes.',
        image: '../assets/cake.jpeg',
        subCategory: 'veg',
        starRating: 4.2,
    },
    {
        id: 16,
        name: 'Nutella Cake',
        price: '749',
        description: 'Rich Nutella flavored cake with a Nutella frosting.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.7,
    },
    {
        id: 17,
        name: 'Raspberry Cake',
        price: '699',
        description: 'Sweet raspberry cake with fresh raspberries.',
        image: '../assets/cake.jpeg',
        subCategory: 'veg',
        starRating: 4.5,
    },
    {
        id: 18,
        name: 'Tiramisu Cake',
        price: '799',
        description: 'Classic Italian Tiramisu cake with coffee and mascarpone.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.8,
    },
    {
        id: 19,
        name: 'Peanut Butter Cake',
        price: '649',
        description: 'Rich peanut butter cake with a chocolate ganache.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.4,
    },
    {
        id: 20,
        name: 'Almond Cake',
        price: '699',
        description: 'Delicious almond cake with a marzipan frosting.',
        image: '../assets/cake.jpeg',
        subCategory: 'veg',
        starRating: 4.6,
    },
];
