export const cakes = [
    {
        id: 41,
        name: 'Mango Mousse Cake',
        description: 'Experience the tropical delight of our Mango Mousse Cake, with a light and airy mousse made from fresh mangoes. This cake offers a smooth and refreshing flavor that’s perfect for a summer treat.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.8,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 349,
                discountedPrice: 319,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 459,
                discountedPrice: 429,
            },
        ],
    },
    {
        id: 42,
        name: 'Chocolate Lava Cake',
        description: 'Indulge in our Chocolate Lava Cake, with a gooey molten center of rich chocolate encased in a soft and fudgy sponge. Each bite delivers a burst of warm chocolate that’s simply irresistible.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.9,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 389,
                discountedPrice: 359,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 499,
                discountedPrice: 469,
            },
        ],
    },
    {
        id: 43,
        name: 'Almond Cake',
        description: 'Relish the nutty flavor of our Almond Cake, with finely chopped almonds mixed into a light sponge and topped with a smooth almond frosting. This cake offers a satisfying crunch and a rich almond taste.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.5,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 379,
                discountedPrice: 349,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 489,
                discountedPrice: 459,
            },
        ],
    },
    {
        id: 44,
        name: 'Raspberry Cheesecake',
        description: 'Enjoy the creamy richness of our Raspberry Cheesecake, with a graham cracker crust and a topping of fresh raspberries. This cheesecake offers a perfect balance of sweet and tart flavors with a creamy texture.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.7,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 399,
                discountedPrice: 369,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 509,
                discountedPrice: 479,
            },
        ],
    },
    {
        id: 45,
        name: 'Hazelnut Cake',
        description: 'Treat yourself to our Hazelnut Cake, featuring layers of hazelnut-infused sponge and a rich hazelnut cream filling. This cake offers a delightful nutty flavor and a smooth, creamy texture.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.6,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 379,
                discountedPrice: 349,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 489,
                discountedPrice: 459,
            },
        ],
    },
    {
        id: 46,
        name: 'Matcha Green Tea Cake',
        description: 'Experience the unique flavor of our Matcha Green Tea Cake, with a light sponge infused with premium matcha green tea powder. This cake offers a subtle, earthy taste with a smooth and delicate texture.',
        image: '../assets/cake.jpeg',
        subCategory: 'Veg',
        starRating: 4.4,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 349,
                discountedPrice: 319,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 459,
                discountedPrice: 429,
            },
        ],
    },
    {
        id: 47,
        name: 'Black Forest Cake',
        description: 'Enjoy the classic flavors of our Black Forest Cake, with layers of chocolate sponge, whipped cream, and cherries. This cake combines rich chocolate with a fruity twist for a deliciously indulgent treat.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.7,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 359,
                discountedPrice: 329,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 469,
                discountedPrice: 439,
            },
        ],
    },
    {
        id: 48,
        name: 'Tiramisu Cake',
        description: 'Indulge in the layers of our Tiramisu Cake, featuring coffee-soaked sponge and a rich mascarpone cream. This cake offers a blend of bold coffee flavor and creamy sweetness for a classic Italian dessert experience.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.8,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 389,
                discountedPrice: 359,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 499,
                discountedPrice: 469,
            },
        ],
    },
    {
        id: 49,
        name: 'Coconut Cake',
        description: 'Enjoy the tropical flavors of our Coconut Cake, with a moist coconut sponge and a creamy coconut frosting. This cake offers a sweet and nutty flavor that transports you to a sunny paradise.',
        image: '../assets/cake.jpeg',
        subCategory: 'Veg',
        starRating: 4.5,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 359,
                discountedPrice: 329,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 469,
                discountedPrice: 439,
            },
        ],
    },
    {
        id: 50,
        name: 'Pistachio Cake',
        description: 'Savor the unique flavor of our Pistachio Cake, with finely ground pistachios mixed into a light sponge and topped with a smooth pistachio frosting. This cake offers a rich and nutty taste with a luxurious texture.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.6,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 379,
                discountedPrice: 349,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 489,
                discountedPrice: 459,
            },
        ],
    },
    {
        id: 51,
        name: 'Pumpkin Spice Cake',
        description: 'Delight in the seasonal flavors of our Pumpkin Spice Cake, with a moist sponge infused with pumpkin puree and warming spices. This cake is topped with a creamy frosting for a comforting and flavorful treat.',
        image: '../assets/cake.jpeg',
        subCategory: 'Veg',
        starRating: 4.4,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 329,
                discountedPrice: 299,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 429,
                discountedPrice: 399,
            },
        ],
    },
    {
        id: 52,
        name: 'Cinnamon Roll Cake',
        description: 'Enjoy the warm and comforting flavors of our Cinnamon Roll Cake, with layers of cinnamon-infused sponge and a creamy frosting. This cake offers a sweet and spicy taste that is perfect for any occasion.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.6,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 359,
                discountedPrice: 329,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 469,
                discountedPrice: 439,
            },
        ],
    },
    {
        id: 53,
        name: 'Peach Cobbler Cake',
        description: 'Enjoy the sweet and tangy flavors of our Peach Cobbler Cake, featuring layers of moist cake with caramelized peaches and a hint of cinnamon. This dessert offers a delightful blend of fruity and spicy notes.',
        image: '../assets/cake.jpeg',
        subCategory: 'Veg',
        starRating: 4.5,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 349,
                discountedPrice: 319,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 459,
                discountedPrice: 429,
            },
        ],
    },
    {
        id: 54,
        name: 'Mango Coconut Cake',
        description: 'Savor the tropical flavors of our Mango Coconut Cake, with a light sponge infused with fresh mangoes and shredded coconut. This cake offers a sweet and exotic taste with a creamy texture.',
        image: '../assets/cake.jpeg',
        subCategory: 'Veg',
        starRating: 4.6,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 359,
                discountedPrice: 329,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 469,
                discountedPrice: 439,
            },
        ],
    },
    {
        id: 55,
        name: 'Raspberry Lemon Cake',
        description: 'Delight in the tangy and sweet flavors of our Raspberry Lemon Cake, with layers of lemon sponge and a vibrant raspberry filling. This cake offers a refreshing and fruity taste with a zesty twist.',
        image: '../assets/cake.jpeg',
        subCategory: 'Veg',
        starRating: 4.4,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 339,
                discountedPrice: 309,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 439,
                discountedPrice: 409,
            },
        ],
    },
    {
        id: 56,
        name: 'Orange Almond Cake',
        description: 'Enjoy the nutty and citrus flavors of our Orange Almond Cake, with a moist sponge infused with orange zest and chopped almonds. This cake offers a unique blend of sweet and tangy with a satisfying crunch.',
        image: '../assets/cake.jpeg',
        subCategory: 'Veg',
        starRating: 4.5,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 349,
                discountedPrice: 319,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 459,
                discountedPrice: 429,
            },
        ],
    },
    {
        id: 57,
        name: 'Tiramisu Cheesecake',
        description: 'Indulge in the rich and creamy flavors of our Tiramisu Cheesecake, combining layers of classic tiramisu with a creamy cheesecake base. This dessert offers a luxurious blend of coffee, mascarpone, and chocolate.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.7,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 399,
                discountedPrice: 369,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 509,
                discountedPrice: 479,
            },
        ],
    },
    {
        id: 58,
        name: 'Apple Spice Cake',
        description: 'Experience the comforting flavors of our Apple Spice Cake, featuring tender chunks of apple and a blend of warm spices. This cake is topped with a creamy frosting and offers a sweet and spiced flavor profile.',
        image: '../assets/cake.jpeg',
        subCategory: 'Veg',
        starRating: 4.5,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 329,
                discountedPrice: 299,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 429,
                discountedPrice: 399,
            },
        ],
    },
    {
        id: 59,
        name: 'Pistachio Rose Cake',
        description: 'Savor the exotic flavors of our Pistachio Rose Cake, with a delicate sponge infused with pistachios and a hint of rosewater. This cake offers a fragrant and nutty taste with a touch of elegance.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.6,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 379,
                discountedPrice: 349,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 489,
                discountedPrice: 459,
            },
        ],
    },
    {
        id: 60,
        name: 'Banana Nut Cake',
        description: 'Enjoy the wholesome flavors of our Banana Nut Cake, with ripe bananas and crunchy nuts mixed into a moist sponge. This cake is topped with a rich nut frosting for a delightful treat.',
        image: '../assets/cake.jpeg',
        subCategory: 'Non-veg',
        starRating: 4.5,
        type: 'cake',
        units: [
            {
                id: 1,
                unit: '1/2 Kg',
                price: 359,
                discountedPrice: 329,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 469,
                discountedPrice: 439,
            },
        ],
    },
];
