export const groceries = [
    {
        id: 1,
        name: 'Cheese',
        description: 'Experience the richness of creamy cheddar cheese, a versatile delight that elevates every dish it touches. Whether melted in sandwiches, sprinkled over salads, or enjoyed on its own, this cheese offers a perfect balance of flavor and texture, making it a must-have for cheese lovers and culinary enthusiasts alike.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Fruit',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
                price: 459,
                discountedPrice: 419,
            },
            {
                id: 2,
                unit: '5 Kg',
                price: 1899,
                discountedPrice: 1709,
            },
        ],
    },
    {
        id: 2,
        name: 'Bananas',
        description: 'Enjoy the natural sweetness of ripe bananas, a go-to snack rich in nutrients and energy. Perfect for smoothies, desserts, or a quick on-the-go bite, these bananas offer a wholesome treat packed with potassium and essential vitamins.',
        image: '../assets/banana.jpeg',
        subCategory: 'Fruit',
        starRating: 4.5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
                price: 60,
                discountedPrice: 50,
            },
            {
                id: 2,
                unit: '5 Kg',
                price: 280,
                discountedPrice: 240,
            },
        ],
    },
    {
        id: 3,
        name: 'Apples',
        description: 'Crisp and juicy, these fresh apples are perfect for snacking, baking, or adding to salads. Their sweet and slightly tart flavor is balanced with a satisfying crunch, making them a favorite choice for healthy eating.',
        image: '../assets/apple.jpeg',
        subCategory: 'Fruit',
        starRating: 4.3,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
                price: 150,
                discountedPrice: 130,
            },
            {
                id: 2,
                unit: '3 Kg',
                price: 420,
                discountedPrice: 370,
            },
        ],
    },
    {
        id: 4,
        name: 'Broccoli',
        description: 'Packed with vitamins and antioxidants, broccoli is a nutritious choice for any meal. This versatile vegetable can be steamed, roasted, or added to soups and stir-fries, delivering a healthy dose of fiber and a subtle earthy flavor.',
        image: '../assets/broccoli.jpeg',
        subCategory: 'Vegetable',
        starRating: 4.7,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '500 gm',
                price: 90,
                discountedPrice: 75,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 170,
                discountedPrice: 150,
            },
        ],
    },
    {
        id: 5,
        name: 'Carrots',
        description: 'Bright and crunchy, these carrots are a versatile staple in many dishes. Whether eaten raw, cooked, or juiced, they bring a sweet flavor and a wealth of nutrients like vitamin A and beta-carotene.',
        image: '../assets/carrots.jpeg',
        subCategory: 'Vegetable',
        starRating: 4.4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
                price: 60,
                discountedPrice: 50,
            },
            {
                id: 2,
                unit: '2 Kg',
                price: 110,
                discountedPrice: 95,
            },
        ],
    },
    {
        id: 6,
        name: 'Chicken Breast',
        description: 'Lean and protein-rich, chicken breast is a favorite choice for healthy meals. Perfect for grilling, roasting, or stir-frying, it offers tender and juicy bites with a mild flavor that pairs well with a variety of spices and marinades.',
        image: '../assets/chicken.jpeg',
        subCategory: 'Meat',
        starRating: 4.8,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '500 gm',
                price: 250,
                discountedPrice: 220,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 470,
                discountedPrice: 430,
            },
        ],
    },
    {
        id: 7,
        name: 'Orange Juice',
        description: 'Freshly squeezed and full of zest, this orange juice is a perfect morning pick-me-up. Packed with vitamin C and natural sweetness, it’s a refreshing drink to start your day or enjoy any time you need a citrusy boost.',
        image: '../assets/orangejuice.jpeg',
        subCategory: 'Beverages',
        starRating: 4.6,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 litre',
                price: 150,
                discountedPrice: 135,
            },
            {
                id: 2,
                unit: '2 litre',
                price: 280,
                discountedPrice: 250,
            },
        ],
    },
    {
        id: 8,
        name: 'Brown Bread',
        description: 'Soft and fiber-rich, this brown bread is a wholesome choice for sandwiches, toasts, or as a side for soups. Made from whole grains, it offers a nutty flavor and a texture that’s both hearty and satisfying.',
        image: '../assets/brownbread.jpeg',
        subCategory: 'Bakery',
        starRating: 4.2,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Pack',
                price: 50,
                discountedPrice: 45,
            },
            {
                id: 2,
                unit: '2 Packs',
                price: 95,
                discountedPrice: 85,
            },
        ],
    },
    {
        id: 9,
        name: 'Butter',
        description: 'Rich and creamy, this butter adds indulgence to every dish. Perfect for spreading on toast, baking, or cooking, it enhances flavors with its smooth and silky texture, making every bite a delight.',
        image: '../assets/butter.jpeg',
        subCategory: 'Dairy',
        starRating: 4.9,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '500 gm',
                price: 180,
                discountedPrice: 160,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 340,
                discountedPrice: 310,
            },
        ],
    },
    {
        id: 10,
        name: 'Tomatoes',
        description: 'Juicy and ripe, these tomatoes are a kitchen essential, whether used in salads, sauces, or cooking. With a perfect balance of sweetness and tang, they add vibrant color and flavor to every dish.',
        image: '../assets/tomatoes.jpeg',
        subCategory: 'Vegetable',
        starRating: 4.3,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
                price: 40,
                discountedPrice: 35,
            },
            {
                id: 2,
                unit: '3 Kg',
                price: 115,
                discountedPrice: 100,
            },
        ],
    },
    {
        id: 11,
        name: 'Basmati Rice',
        description: 'Long-grain and aromatic, this basmati rice is perfect for biryanis, pulaos, and everyday meals. Its fluffy texture and rich fragrance make it a favorite staple in many kitchens.',
        image: '../assets/basmati.jpeg',
        subCategory: 'Grains',
        starRating: 4.7,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
                price: 120,
                discountedPrice: 110,
            },
            {
                id: 2,
                unit: '5 Kg',
                price: 550,
                discountedPrice: 510,
            },
        ],
    },
    {
        id: 12,
        name: 'Spinach',
        description: 'Fresh and leafy, spinach is a nutritious green that’s versatile and easy to include in your meals. Whether used in salads, smoothies, or cooked dishes, it adds a boost of vitamins and minerals with its earthy flavor.',
        image: '../assets/spinach.jpeg',
        subCategory: 'Vegetable',
        starRating: 4.5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '250 gm',
                price: 40,
                discountedPrice: 35,
            },
            {
                id: 2,
                unit: '500 gm',
                price: 75,
                discountedPrice: 65,
            },
        ],
    },
    {
        id: 13,
        name: 'Whole Wheat Flour',
        description: 'Ground from premium whole grains, this wheat flour offers a fine texture ideal for making soft chapatis, bread, and other baked goods. Nutritious and rich in fiber, it’s a healthy choice for everyday cooking.',
        image: '../assets/wholewheat.jpeg',
        subCategory: 'Grains',
        starRating: 4.6,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
                price: 40,
                discountedPrice: 35,
            },
            {
                id: 2,
                unit: '5 Kg',
                price: 180,
                discountedPrice: 160,
            },
        ],
    },
    {
        id: 14,
        name: 'Strawberries',
        description: 'Sweet and tangy, these strawberries are bursting with flavor. Perfect for snacking, desserts, or blending into smoothies, they add a touch of freshness and color to any dish.',
        image: '../assets/strawberries.jpeg',
        subCategory: 'Fruit',
        starRating: 4.8,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '250 gm',
                price: 150,
                discountedPrice: 130,
            },
            {
                id: 2,
                unit: '500 gm',
                price: 280,
                discountedPrice: 250,
            },
        ],
    },
    {
        id: 15,
        name: 'Olive Oil',
        description: 'Cold-pressed and rich in flavor, this extra virgin olive oil is perfect for cooking, dressing salads, and drizzling over dishes. Its robust taste enhances your recipes while offering numerous health benefits.',
        image: '../assets/oliveoil.jpeg',
        subCategory: 'Cooking Oils',
        starRating: 4.9,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '500 ml',
                price: 450,
                discountedPrice: 410,
            },
            {
                id: 2,
                unit: '1 litre',
                price: 850,
                discountedPrice: 790,
            },
        ],
    },
    {
        id: 16,
        name: 'Potatoes',
        description: 'Versatile and essential, these potatoes can be baked, mashed, fried, or cooked in a variety of ways. With a starchy texture and a mild flavor, they’re a staple ingredient in countless recipes.',
        image: '../assets/potatoes.jpeg',
        subCategory: 'Vegetable',
        starRating: 4.4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
                price: 30,
                discountedPrice: 25,
            },
            {
                id: 2,
                unit: '5 Kg',
                price: 140,
                discountedPrice: 120,
            },
        ],
    },
    {
        id: 17,
        name: 'Green Peas',
        description: 'Tender and sweet, green peas are a versatile ingredient that can be used in soups, stews, salads, or simply steamed. Packed with nutrients, they bring a pop of color and flavor to your meals.',
        image: '../assets/greenpeas.jpeg',
        subCategory: 'Vegetable',
        starRating: 4.5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '500 gm',
                price: 70,
                discountedPrice: 60,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 130,
                discountedPrice: 115,
            },
        ],
    },
    {
        id: 18,
        name: 'Almonds',
        description: 'Crunchy and nutrient-dense, these almonds are perfect for snacking or adding to dishes. Rich in healthy fats, protein, and fiber, they offer a wholesome treat with a slightly sweet and nutty flavor.',
        image: '../assets/almonds.jpeg',
        subCategory: 'Nuts',
        starRating: 4.9,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '250 gm',
                price: 350,
                discountedPrice: 320,
            },
            {
                id: 2,
                unit: '500 gm',
                price: 670,
                discountedPrice: 620,
            },
        ],
    },
    {
        id: 19,
        name: 'Chickpeas',
        description: 'Rich in protein and fiber, these chickpeas are a versatile ingredient in many cuisines. Whether cooked in curries, added to salads, or made into hummus, they offer a hearty texture and a nutty flavor.',
        image: '../assets/chickpeas.jpeg',
        subCategory: 'Legumes',
        starRating: 4.6,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
                price: 90,
                discountedPrice: 80,
            },
            {
                id: 2,
                unit: '5 Kg',
                price: 420,
                discountedPrice: 380,
            },
        ],
    },
    {
        id: 20,
        name: 'Oats',
        description: 'Start your day with a wholesome bowl of oats, packed with fiber and essential nutrients. Whether cooked into porridge, used in baking, or blended into smoothies, these oats provide a versatile and nutritious option for your meals.',
        image: '../assets/oats.jpeg',
        subCategory: 'Grains',
        starRating: 4.8,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '500 gm',
                price: 150,
                discountedPrice: 135,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 280,
                discountedPrice: 250,
            },
        ],
    }

];
