export const groceries = [
    {
        id: 1,
        name: 'Cheese',
        description: 'Experience the richness of creamy cheddar cheese, a versatile delight that elevates every dish it touches. Whether melted in sandwiches, sprinkled over salads, or enjoyed on its own, this cheese offers a perfect balance of flavor and texture, making it a must-have for cheese lovers and culinary enthusiasts alike.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Fruit',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '250 gm',
                price: 120,
                discountedPrice: 100,
            },
            {
                id: 2,
                unit: '500 gm',
                price: 220,
                discountedPrice: 200,
            },
            {
                id: 3,
                unit: '1 Kg',
                price: 459,
                discountedPrice: 419,
            },
        ],
    },
    {
        id: 2,
        name: 'Organic Apples',
        description: 'Fresh, crisp, and juicy organic apples that are perfect for snacking or baking. These apples offer a delightful balance of sweetness and tartness, making them a favorite among health-conscious individuals and culinary enthusiasts.',
        image: '../assets/grocery_apples.jpeg',
        subCategory: 'Fruit',
        starRating: 5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '500 gm',
                price: 80,
                discountedPrice: 70,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 150,
                discountedPrice: 140,
            },
            {
                id: 3,
                unit: '2 Kg',
                price: 290,
                discountedPrice: 270,
            },
        ],
    },
    {
        id: 3,
        name: 'Almonds',
        description: 'Premium quality almonds that are crunchy and rich in nutrients. Ideal for snacking, baking, or adding to salads and dishes for a healthy crunch. These almonds are roasted to perfection for enhanced flavor.',
        image: '../assets/grocery_almonds.jpeg',
        subCategory: 'Nuts',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '200 gm',
                price: 250,
                discountedPrice: 230,
            },
            {
                id: 2,
                unit: '500 gm',
                price: 600,
                discountedPrice: 550,
            },
            {
                id: 3,
                unit: '1 Kg',
                price: 1150,
                discountedPrice: 1100,
            },
        ],
    },
    {
        id: 4,
        name: 'Whole Wheat Flour',
        description: 'Nutritious and fresh whole wheat flour, ideal for making breads, rotis, and other baked goods. Packed with dietary fiber and essential nutrients, it is a healthy choice for a balanced diet.',
        image: '../assets/grocery_flour.jpeg',
        subCategory: 'Baking',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
                price: 70,
                discountedPrice: 65,
            },
            {
                id: 2,
                unit: '5 Kg',
                price: 300,
                discountedPrice: 280,
            },

        ],
    },
    {
        id: 5,
        name: 'Olive Oil',
        description: 'High-quality extra virgin olive oil, perfect for cooking, dressing, and drizzling. This oil adds a rich flavor to your dishes and is known for its health benefits, including being a source of healthy fats.',
        image: '../assets/grocery_olive_oil.jpeg',
        subCategory: 'Oils',
        starRating: 5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '500 ml',
                price: 300,
                discountedPrice: 280,
            },
            {
                id: 2,
                unit: '1 L',
                price: 550,
                discountedPrice: 500,
            },
            {
                id: 3,
                unit: '2 L',
                price: 1000,
                discountedPrice: 950,
            },
        ],
    },
    {
        id: 6,
        name: 'Rice',
        description: 'Long-grain basmati rice, known for its fragrant aroma and fluffy texture when cooked. Ideal for making biryanis, pilafs, and other rice dishes. This rice is sourced from the finest regions for superior quality.',
        image: '../assets/grocery_rice.jpeg',
        subCategory: 'Grains',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
                price: 90,
                discountedPrice: 85,
            },
            {
                id: 2,
                unit: '5 Kg',
                price: 400,
                discountedPrice: 380,
            },
            {
                id: 3,
                unit: '10 Kg',
                price: 750,
                discountedPrice: 700,
            },
        ],
    },
    {
        id: 7,
        name: 'Chicken Breast',
        description: 'Tender and juicy chicken breasts, perfect for grilling, baking, or stir-frying. These chicken breasts are lean and high in protein, making them a great choice for a healthy diet.',
        image: '../assets/grocery_chicken.jpeg',
        subCategory: 'Meat',
        starRating: 5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '500 gm',
                price: 200,
                discountedPrice: 180,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 400,
                discountedPrice: 360,
            },

        ],
    },
    {
        id: 8,
        name: 'Greek Yogurt',
        description: 'Creamy and thick Greek yogurt, packed with protein and probiotics. Ideal for a nutritious breakfast or as a base for smoothies and desserts. Its tangy flavor pairs well with fruits and honey.',
        image: '../assets/grocery_yogurt.jpeg',
        subCategory: 'Dairy',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '200 gm',
                price: 60,
                discountedPrice: 55,
            },
            {
                id: 2,
                unit: '500 gm',
                price: 140,
                discountedPrice: 130,
            },
            {
                id: 3,
                unit: '1 Kg',
                price: 260,
                discountedPrice: 240,
            },
        ],
    },
    {
        id: 9,
        name: 'Organic Spinach',
        description: 'Fresh and nutrient-rich organic spinach, perfect for salads, smoothies, and cooking. This spinach is grown without pesticides, ensuring a healthier choice for you and your family.',
        image: '../assets/grocery_spinach.jpeg',
        subCategory: 'Vegetables',
        starRating: 5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '250 gm',
                price: 50,
                discountedPrice: 45,
            },
            {
                id: 2,
                unit: '500 gm',
                price: 90,
                discountedPrice: 85,
            },
            {
                id: 3,
                unit: '1 Kg',
                price: 170,
                discountedPrice: 150,
            },
        ],
    },
    {
        id: 10,
        name: 'Pasta',
        description: 'Delicious pasta made from high-quality durum wheat, perfect for a variety of dishes from classic spaghetti to lasagna. This pasta cooks to a perfect al dente texture, making your meals enjoyable.',
        image: '../assets/grocery_pasta.jpeg',
        subCategory: 'Baking',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '500 gm',
                price: 100,
                discountedPrice: 90,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 190,
                discountedPrice: 170,
            },

        ],
    },
    {
        id: 11,
        name: 'Tomato Sauce',
        description: 'Rich and flavorful tomato sauce, perfect for pizzas, pasta dishes, and more. Made from ripe tomatoes and seasoned with herbs and spices for a delicious and versatile condiment.',
        image: '../assets/grocery_tomato_sauce.jpeg',
        subCategory: 'Sauces',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '250 ml',
                price: 70,
                discountedPrice: 65,
            },
            {
                id: 2,
                unit: '500 ml',
                price: 130,
                discountedPrice: 120,
            },

        ],
    },
    {
        id: 12,
        name: 'Honey',
        description: 'Pure and natural honey, rich in flavor and packed with health benefits. Ideal for sweetening tea, drizzling over yogurt, or using in baking. This honey is sourced from the finest beekeepers for optimal quality.',
        image: '../assets/grocery_honey.jpeg',
        subCategory: 'Sweeteners',
        starRating: 5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '250 gm',
                price: 150,
                discountedPrice: 140,
            },
            {
                id: 2,
                unit: '500 gm',
                price: 280,
                discountedPrice: 260,
            },
            {
                id: 3,
                unit: '1 Kg',
                price: 540,
                discountedPrice: 500,
            },
        ],
    },
    {
        id: 13,
        name: 'Avocados',
        description: 'Creamy and nutritious avocados, perfect for salads, sandwiches, and making guacamole. Rich in healthy fats and vitamins, they add a delicious, buttery flavor to any dish.',
        image: '../assets/grocery_avocado.jpeg',
        subCategory: 'Fruit',
        starRating: 5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Pc',
                price: 70,
                discountedPrice: 65,
            },
            {
                id: 2,
                unit: '4 Pc',
                price: 260,
                discountedPrice: 240,
            },
            {
                id: 3,
                unit: '6 Pc',
                price: 380,
                discountedPrice: 350,
            },
        ],
    },
    {
        id: 14,
        name: 'Brown Sugar',
        description: 'Rich and moist brown sugar, ideal for baking and cooking. It adds a deeper flavor and a touch of caramel to your recipes, perfect for cookies, cakes, and sauces.',
        image: '../assets/grocery_brown_sugar.jpeg',
        subCategory: 'Sweeteners',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '500 gm',
                price: 80,
                discountedPrice: 70,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 150,
                discountedPrice: 140,
            },
            {
                id: 3,
                unit: '2 Kg',
                price: 290,
                discountedPrice: 270,
            },
        ],
    },
    {
        id: 15,
        name: 'Green Beans',
        description: 'Fresh green beans, crisp and tender. Ideal for steaming, sautéing, or adding to salads and casseroles. Packed with vitamins and fiber, they’re a healthy and tasty vegetable choice.',
        image: '../assets/grocery_green_beans.jpeg',
        subCategory: 'Vegetables',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '250 gm',
                price: 60,
                discountedPrice: 55,
            },
            {
                id: 2,
                unit: '500 gm',
                price: 110,
                discountedPrice: 100,
            },

        ],
    },
    {
        id: 16,
        name: 'Canned Tuna',
        description: 'High-quality canned tuna, perfect for quick meals and sandwiches. Packed with protein and Omega-3 fatty acids, it’s a convenient and nutritious option for busy days.',
        image: '../assets/grocery_tuna.jpeg',
        subCategory: 'Canned Goods',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '150 gm',
                price: 50,
                discountedPrice: 45,
            },
            {
                id: 2,
                unit: '300 gm',
                price: 90,
                discountedPrice: 85,
            },
            {
                id: 3,
                unit: '500 gm',
                price: 150,
                discountedPrice: 140,
            },
        ],
    },
    {
        id: 17,
        name: 'Granola Bars',
        description: 'Tasty and wholesome granola bars, perfect for a quick snack or a healthy breakfast on the go. Made with oats, nuts, and honey, they provide a good balance of energy and nutrients.',
        image: '../assets/grocery_granola_bars.jpeg',
        subCategory: 'Snacks',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '6 Bars',
                price: 120,
                discountedPrice: 110,
            },
            {
                id: 2,
                unit: '12 Bars',
                price: 230,
                discountedPrice: 210,
            },

        ],
    },
    {
        id: 18,
        name: 'Oats',
        description: 'Nutritious and versatile oats, ideal for breakfast or baking. Rich in fiber and protein, they’re perfect for making oatmeal, smoothies, or as an ingredient in cookies and bars.',
        image: '../assets/grocery_oats.jpeg',
        subCategory: 'Grains',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '500 gm',
                price: 90,
                discountedPrice: 80,
            },
            {
                id: 2,
                unit: '1 Kg',
                price: 170,
                discountedPrice: 150,
            },
            {
                id: 3,
                unit: '2 Kg',
                price: 330,
                discountedPrice: 300,
            },
        ],
    },
    {
        id: 19,
        name: 'Dark Chocolate',
        description: 'Rich and indulgent dark chocolate, perfect for a sweet treat or as an ingredient in baking. Made with high-quality cocoa, it offers a deep, intense flavor and smooth texture.',
        image: '../assets/grocery_dark_chocolate.jpeg',
        subCategory: 'Snacks',
        starRating: 5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '100 gm',
                price: 90,
                discountedPrice: 80,
            },
            {
                id: 2,
                unit: '200 gm',
                price: 160,
                discountedPrice: 150,
            },
            {
                id: 3,
                unit: '500 gm',
                price: 350,
                discountedPrice: 320,
            },
        ],
    },
    {
        id: 20,
        name: 'Almond Milk',
        description: 'Creamy and dairy-free almond milk, perfect for smoothies, coffee, or as a substitute in baking. Made from high-quality almonds, it offers a delicious and nutritious alternative to cow’s milk.',
        image: '../assets/grocery_almond_milk.jpeg',
        subCategory: 'Dairy Alternatives',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 L',
                price: 110,
                discountedPrice: 100,
            },
            {
                id: 2,
                unit: '2 L',
                price: 210,
                discountedPrice: 200,
            },
        ],
    },
];
