export const groceries = [
    {
        id: 1,
        name: 'Cheese',
        description: 'Experience the richness of creamy cheddar cheese, a versatile delight that elevates every dish it touches. Whether melted in sandwiches, sprinkled over salads, or enjoyed on its own, this cheese offers a perfect balance of flavor and texture, making it a must-have for cheese lovers and culinary enthusiasts alike.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Fruit',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
                price: 459,
                discountedPrice: 419,
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 2,
        name: 'Carrot',
        price: 319,
        discountedPrice: 279,
        description: 'Enjoy the vibrant freshness of orange carrots, packed with essential nutrients and a satisfying crunch. These versatile vegetables are perfect for adding a pop of color and flavor to salads, soups, and stir-fries. Whether eaten raw as a healthy snack or cooked in your favorite dishes, carrots bring a wholesome taste to your meals.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Dairy',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 3,
        name: 'Broccoli',
        price: 359,
        discountedPrice: 319,
        description: 'Savor the healthy, green goodness of fresh broccoli, a nutrient-rich vegetable known for its versatility. Ideal for steaming, stir-frying, or roasting, broccoli adds a hearty texture and subtle flavor to a variety of dishes. Whether you\'re preparing a wholesome side or a main dish, broccoli is a go-to choice for nutritious meals.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Pulses',
        starRating: 5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 4,
        name: 'Tomato',
        price: 259,
        discountedPrice: 219,
        description: 'Bursting with juiciness and rich flavor, fresh red tomatoes are a kitchen essential. These ripe, vibrant tomatoes enhance salads, sauces, and sandwiches with their natural sweetness and tang. Whether chopped, sliced, or pureed, tomatoes bring a refreshing taste and bright color to countless dishes, making them a must-have ingredient.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Fruit',
        starRating: 3,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 5,
        name: 'Butter',
        price: 329,
        discountedPrice: 289,
        description: 'Indulge in the creamy richness of unsalted butter, a staple ingredient for cooking, baking, and spreading. Its smooth texture and mild flavor make it ideal for everything from sautéing vegetables to enhancing the taste of freshly baked bread. Perfect for those who appreciate the pure, natural taste of high-quality butter.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Fruit',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 6,
        name: 'Milk',
        price: 369,
        discountedPrice: 329,
        description: 'Enjoy the fresh, creamy goodness of whole milk, a versatile dairy product that’s perfect for drinking, cooking, or baking. Rich in essential nutrients and with a smooth, satisfying flavor, this milk is an excellent choice for adding richness to your recipes or simply enjoying as a refreshing beverage.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Fruit',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 7,
        name: 'Spinach',
        price: 289,
        discountedPrice: 249,
        description: 'Organic, fresh green spinach brings a burst of nutrition to your meals. This leafy green is rich in vitamins and minerals, making it perfect for salads, smoothies, or cooked dishes. Whether you’re preparing a light salad or a hearty stew, spinach adds both flavor and health benefits to your table.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Cereals',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 8,
        name: 'Pasta',
        price: 349,
        discountedPrice: 309,
        description: 'Enjoy the wholesome taste of organic whole wheat pasta, a nutritious and hearty base for a wide variety of dishes. This pasta\'s firm texture and rich, earthy flavor make it perfect for pairing with your favorite sauces, vegetables, or proteins, providing a satisfying and healthy meal option for any occasion.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Fruit',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 9,
        name: 'Eggs',
        price: 279,
        discountedPrice: 239,
        description: 'Farm-fresh organic brown eggs are a versatile kitchen staple, known for their rich flavor and high nutritional value. Ideal for breakfast, baking, or cooking, these eggs bring a natural, wholesome taste to every dish. Whether boiled, scrambled, or baked into your favorite recipes, they are a must-have for any meal.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Fruit',
        starRating: 5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 10,
        name: 'Banana',
        price: 279,
        discountedPrice: 239,
        description: 'Sweet, organic yellow bananas are the perfect snack, offering a quick and nutritious energy boost. These bananas are not only delicious on their own but also a great addition to smoothies, desserts, and breakfast bowls. Their natural sweetness and creamy texture make them a versatile and healthy choice for any time of day.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Fruit',
        starRating: 4.5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 11,
        name: 'Fish',
        price: 459,
        discountedPrice: 419,
        description: 'Fresh, healthy salmon fish is a rich source of omega-3 fatty acids, making it a nutritious and delicious choice for any meal. Whether grilled, baked, or pan-seared, salmon offers a tender texture and a rich, savory flavor that pairs well with a variety of seasonings and sides, making it a favorite for seafood lovers.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Fruit',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 12,
        name: 'Onion',
        price: 299,
        discountedPrice: 259,
        description: 'Fresh and crunchy white onions are a kitchen staple, known for their ability to enhance the flavor of almost any dish. Whether chopped for a salad, sautéed as a base for soups, or caramelized for a sweet and savory side, onions bring depth and complexity to your cooking with their distinct, versatile flavor.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Meat',
        starRating: 3,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 13,
        name: 'Potato',
        price: 199,
        discountedPrice: 159,
        description: 'Versatile and hearty, fresh potatoes are a staple in kitchens worldwide. Whether baked, mashed, or fried, these earthy potatoes are perfect for a wide range of comforting dishes. With their mild flavor and firm texture, they are an essential ingredient in both traditional and modern recipes.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Vegetable',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 14,
        name: 'Apple',
        price: 359,
        discountedPrice: 319,
        description: 'Crisp and sweet, fresh apples are a nutritious snack packed with natural flavor. Enjoy them as a quick snack or use them in a variety of recipes, from salads to desserts. With their vibrant color and satisfying crunch, apples are a favorite choice for healthy eating.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Fruit',
        starRating: 4.5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 15,
        name: 'Cabbage',
        price: 279,
        discountedPrice: 239,
        description: 'Fresh, leafy cabbage is a versatile vegetable that adds a touch of crunch to salads, soups, and stir-fries. Known for its mild flavor and firm texture, cabbage is a popular ingredient in a variety of dishes and is rich in vitamins, making it a healthy choice for your meals.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Vegetable',
        starRating: 3.5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 16,
        name: 'Garlic',
        price: 199,
        discountedPrice: 169,
        description: 'Aromatic and pungent, fresh garlic is a powerful ingredient that enhances the flavor of a wide variety of dishes. Whether used in cooking or as a seasoning, garlic is a must-have in any kitchen, bringing depth and complexity to everything from sauces to stews.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Vegetable',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 17,
        name: 'Mango',
        price: 399,
        discountedPrice: 349,
        description: 'Juicy and sweet, fresh mangoes are a tropical delight that bring a burst of flavor to any dish. Perfect for smoothies, desserts, or simply enjoyed on their own, these vibrant fruits offer a rich, creamy texture that is loved by people of all ages.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Fruit',
        starRating: 5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 18,
        name: 'Peas',
        price: 249,
        discountedPrice: 209,
        description: 'Tender and sweet, fresh green peas add a burst of color and flavor to any dish. Whether tossed in salads, added to soups, or used as a side, peas are a versatile ingredient that complement a variety of meals. Packed with nutrients, they are a healthy addition to your diet.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Vegetable',
        starRating: 4,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 19,
        name: 'Pumpkin',
        price: 239,
        discountedPrice: 199,
        description: 'Fresh pumpkins are a nutritious and versatile vegetable that can be used in soups, stews, and desserts. Known for their sweet, earthy flavor, pumpkins are perfect for roasting or baking, bringing a natural warmth to your meals during any season.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Vegetable',
        starRating: 3.5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
    {
        id: 20,
        name: 'Lemon',
        price: 199,
        discountedPrice: 159,
        description: 'Bright and tangy, fresh lemons are a must-have for adding a zesty kick to your dishes. Perfect for flavoring drinks, salads, and marinades, these citrus fruits are packed with vitamin C and bring a refreshing taste that enhances both savory and sweet recipes.',
        image: '../assets/grocery.jpeg',
        subCategory: 'Fruit',
        starRating: 4.5,
        type: 'grocery',
        units: [
            {
                id: 1,
                unit: '1 Kg',
            },
            {
                id: 2,
                unit: '5 Kg',
            },
        ],
    },
];
