export const restaurants = [
    {
        id: 1,
        name: 'Chicken Fried Rice',
        description: 'A delightful mix of tender chicken pieces, fresh vegetables, and perfectly cooked rice, all stir-fried together to create a flavorful and satisfying dish. Each bite offers a balance of savory flavors and a touch of spice, making it a great choice for a quick and tasty meal any time of the day.',
        image: '../assets/rice.png',
        subCategory: 'Non-veg',
        starRating: 3.1,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 249,
                discountedPrice: 224,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 459,
                discountedPrice: 419,
            },
        ],
    },
    {
        id: 2,
        name: 'Veg Pulao',
        description: 'Fragrant basmati rice cooked with an assortment of mixed vegetables and aromatic spices. This dish combines the natural sweetness of the vegetables with the subtle heat of the spices, creating a harmonious blend of flavors. Ideal for a light, nutritious meal that’s both satisfying and delicious.',
        image: '../assets/rice.png',
        subCategory: 'Veg',
        starRating: 4.2,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 229,
                discountedPrice: 199,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 429,
                discountedPrice: 389,
            },
        ],
    },
    {
        id: 3,
        name: 'Paneer Biryani',
        description: 'A delectable biryani made with marinated paneer and aromatic basmati rice, infused with a blend of rich spices. This dish features tender paneer cubes cooked to perfection with fragrant rice, offering a satisfying and flavorful experience. It’s a must-try for those who enjoy a hearty and spiced rice dish.',
        image: '../assets/rice.png',
        subCategory: 'Veg',
        starRating: 4.5,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 279,
                discountedPrice: 249,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 499,
                discountedPrice: 459,
            },
        ],
    },
    {
        id: 4,
        name: 'Egg Fried Rice',
        description: 'A classic fried rice dish featuring fluffy rice stir-fried with eggs and fresh vegetables. The eggs add a creamy texture, while the vegetables provide a crunch and burst of flavor. This quick and easy meal is perfect for a satisfying lunch or dinner, with a hint of savory seasoning.',
        image: '../assets/rice.png',
        subCategory: 'Non-veg',
        starRating: 4.0,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 219,
                discountedPrice: 199,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 399,
                discountedPrice: 359,
            },
        ],
    },
    {
        id: 5,
        name: 'Mutton Biryani',
        description: 'Rich and aromatic mutton biryani, where succulent pieces of mutton are slow-cooked with basmati rice and a blend of spices. Each mouthful offers a burst of flavors from the tender meat and fragrant rice, making it a luxurious and indulgent choice for any biryani lover.',
        image: '../assets/rice.png',
        subCategory: 'Non-veg',
        starRating: 4.8,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 349,
                discountedPrice: 319,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 649,
                discountedPrice: 599,
            },
        ],
    },
    {
        id: 6,
        name: 'Mixed Veg Fried Rice',
        description: 'A vibrant and healthy stir-fried rice dish packed with a colorful mix of fresh vegetables. The rice is seasoned with light spices, allowing the natural flavors of the vegetables to shine through. It’s a nutritious option that’s perfect for a quick and wholesome meal.',
        image: '../assets/rice.png',
        subCategory: 'Veg',
        starRating: 4.1,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 199,
                discountedPrice: 179,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 359,
                discountedPrice: 329,
            },
        ],
    },
    {
        id: 7,
        name: 'Hyderabadi Chicken Biryani',
        description: 'A flavorful and spicy biryani featuring tender chicken cooked with aromatic basmati rice and a blend of traditional spices. The dish is renowned for its rich taste and vibrant colors, making it a favorite among biryani enthusiasts looking for a robust and satisfying meal.',
        image: '../assets/rice.png',
        subCategory: 'Non-veg',
        starRating: 4.7,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 329,
                discountedPrice: 299,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 619,
                discountedPrice: 579,
            },
        ],
    },
    {
        id: 8,
        name: 'Vegetable Hakka Noodles',
        description: 'Delicious stir-fried noodles tossed with a variety of fresh vegetables in a tangy and slightly spicy sauce. This dish combines the crunch of the vegetables with the softness of the noodles, creating a balanced and flavorful meal that’s both satisfying and easy to enjoy.',
        image: '../assets/rice.png',
        subCategory: 'Veg',
        starRating: 3.9,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 179,
                discountedPrice: 159,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 339,
                discountedPrice: 309,
            },
        ],
    },
    {
        id: 9,
        name: 'Chicken Schezwan Rice',
        description: 'A spicy and flavorful rice dish featuring tender pieces of chicken and a blend of vegetables cooked in Schezwan sauce. The bold flavors and slight heat make this dish a delicious option for those who enjoy a bit of spice in their meal.',
        image: '../assets/rice.png',
        subCategory: 'Non-veg',
        starRating: 4.3,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 259,
                discountedPrice: 229,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 479,
                discountedPrice: 439,
            },
        ],
    },
    {
        id: 10,
        name: 'Veg Biryani',
        description: 'Aromatic basmati rice cooked with a blend of fresh vegetables and spices. This dish offers a delightful combination of textures and flavors, with the vegetables adding a satisfying crunch and the spices enhancing the overall taste. It’s a well-balanced and flavorful option for vegetarians.',
        image: '../assets/rice.png',
        subCategory: 'Veg',
        starRating: 4.2,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 239,
                discountedPrice: 209,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 439,
                discountedPrice: 399,
            },
        ],
    },
    {
        id: 11,
        name: 'Prawn Fried Rice',
        description: 'A savory fried rice dish featuring succulent prawns stir-fried with rice and a mix of vegetables. The prawns add a delicious seafood flavor, while the vegetables provide a satisfying crunch. This dish is seasoned to perfection, offering a delightful combination of flavors and textures.',
        image: '../assets/rice.png',
        subCategory: 'Non-veg',
        starRating: 4.6,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 319,
                discountedPrice: 289,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 579,
                discountedPrice: 529,
            },
        ],
    },
    {
        id: 12,
        name: 'Veg Manchurian Rice',
        description: 'Crispy veg Manchurian balls served with flavorful fried rice. The Manchurian balls are coated in a tangy and spicy sauce, perfectly complementing the rice. This dish offers a satisfying combination of crunch and savory flavors, ideal for a hearty and flavorful meal.',
        image: '../assets/rice.png',
        subCategory: 'Veg',
        starRating: 4.0,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 199,
                discountedPrice: 179,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 369,
                discountedPrice: 339,
            },
        ],
    },
    {
        id: 13,
        name: 'Paneer Butter Masala',
        description: 'A creamy and rich curry made with tender paneer cubes cooked in a luscious tomato-based gravy. The buttery and mildly spiced sauce is perfect for pairing with naan or rice, offering a delightful experience for lovers of North Indian cuisine.',
        image: '../assets/paneer.png',
        subCategory: 'Veg',
        starRating: 4.5,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 229,
                discountedPrice: 209,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 399,
                discountedPrice: 369,
            },
        ],
    },
    {
        id: 14,
        name: 'Chicken Biryani',
        description: 'Aromatic basmati rice layered with tender chicken pieces cooked in a blend of flavorful spices. This biryani is served with raita, offering a perfect balance of spices, savory flavors, and a hint of freshness from the yogurt.',
        image: '../assets/biryani.png',
        subCategory: 'Non-Veg',
        starRating: 4.7,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 249,
                discountedPrice: 229,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 449,
                discountedPrice: 419,
            },
        ],
    },
    {
        id: 15,
        name: 'Chole Bhature',
        description: 'A classic North Indian dish featuring spicy chickpeas cooked in a tangy and aromatic gravy, served with fluffy and deep-fried bhature. This meal is perfect for a filling and flavorful indulgence.',
        image: '../assets/chole.png',
        subCategory: 'Veg',
        starRating: 4.2,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 179,
                discountedPrice: 159,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 299,
                discountedPrice: 279,
            },
        ],
    },
    {
        id: 16,
        name: 'Mutton Rogan Josh',
        description: 'A rich and flavorful curry featuring tender mutton cooked in a blend of spices and yogurt. This Kashmiri delicacy is best enjoyed with naan or steamed rice, offering a mouthwatering experience for mutton lovers.',
        image: '../assets/mutton.png',
        subCategory: 'Non-Veg',
        starRating: 4.8,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 349,
                discountedPrice: 319,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 599,
                discountedPrice: 569,
            },
        ],
    },
    {
        id: 17,
        name: 'Veg Hakka Noodles',
        description: 'Stir-fried noodles tossed with a mix of fresh vegetables, soy sauce, and a hint of garlic. This Indo-Chinese favorite offers a delightful balance of flavors and is perfect as a standalone dish or with a side of Manchurian.',
        image: '../assets/noodles.png',
        subCategory: 'Veg',
        starRating: 4.3,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 149,
                discountedPrice: 129,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 269,
                discountedPrice: 249,
            },
        ],
    },
    {
        id: 18,
        name: 'Fish Curry',
        description: 'A flavorful coastal dish featuring tender fish cooked in a spicy and tangy curry. The use of coconut milk and aromatic spices gives this curry a delightful taste, making it a perfect companion for steamed rice.',
        image: '../assets/fish.png',
        subCategory: 'Non-Veg',
        starRating: 4.6,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 269,
                discountedPrice: 239,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 469,
                discountedPrice: 439,
            },
        ],
    },
    {
        id: 19,
        name: 'Dal Makhani',
        description: 'A rich and creamy lentil dish made with black lentils and kidney beans slow-cooked with butter, cream, and spices. This comforting dish pairs perfectly with naan or steamed rice and is a staple in North Indian cuisine.',
        image: '../assets/dal.png',
        subCategory: 'Veg',
        starRating: 4.4,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 179,
                discountedPrice: 159,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 299,
                discountedPrice: 279,
            },
        ],
    },
    {
        id: 20,
        name: 'Butter Chicken',
        description: 'A creamy and mildly spiced dish featuring succulent chicken pieces cooked in a rich tomato and butter gravy. This North Indian favorite is best paired with naan or rice, offering a luxurious and flavorful dining experience.',
        image: '../assets/butter-chicken.png',
        subCategory: 'Non-Veg',
        starRating: 4.7,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 249,
                discountedPrice: 229,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 449,
                discountedPrice: 419,
            },
        ],
    },

];
