export const restaurants = [
    {
        id: 1,
        name: 'Chicken Fried Rice',
        price: '149',
        description: 'A delightful mix of tender chicken pieces, fresh vegetables, and perfectly cooked rice, all stir-fried together to create a flavorful and satisfying dish. Each bite offers a balance of savory flavors and a touch of spice, making it a great choice for a quick and tasty meal any time of the day.',
        image: '../assets/rice.png',
        subCategory: 'Non-veg',
        starRating: 3.1,
        type: 'restaurant',
    },
    {
        id: 2,
        name: 'Veg Pulao',
        price: '129',
        description: 'Fragrant basmati rice cooked with an assortment of mixed vegetables and aromatic spices. This dish combines the natural sweetness of the vegetables with the subtle heat of the spices, creating a harmonious blend of flavors. Ideal for a light, nutritious meal that’s both satisfying and delicious.',
        image: '../assets/rice.png',
        subCategory: 'Veg',
        starRating: 4.2,
        type: 'restaurant',
    },
    {
        id: 3,
        name: 'Paneer Biryani',
        price: '199',
        description: 'A delectable biryani made with marinated paneer and aromatic basmati rice, infused with a blend of rich spices. This dish features tender paneer cubes cooked to perfection with fragrant rice, offering a satisfying and flavorful experience. It’s a must-try for those who enjoy a hearty and spiced rice dish.',
        image: '../assets/rice.png',
        subCategory: 'Veg',
        starRating: 4.5,
        type: 'restaurant',
    },
    {
        id: 4,
        name: 'Egg Fried Rice',
        price: '139',
        description: 'A classic fried rice dish featuring fluffy rice stir-fried with eggs and fresh vegetables. The eggs add a creamy texture, while the vegetables provide a crunch and burst of flavor. This quick and easy meal is perfect for a satisfying lunch or dinner, with a hint of savory seasoning.',
        image: '../assets/rice.png',
        subCategory: 'Non-veg',
        starRating: 4.0,
        type: 'restaurant',
    },
    {
        id: 5,
        name: 'Mutton Biryani',
        price: '249',
        description: 'Rich and aromatic mutton biryani, where succulent pieces of mutton are slow-cooked with basmati rice and a blend of spices. Each mouthful offers a burst of flavors from the tender meat and fragrant rice, making it a luxurious and indulgent choice for any biryani lover.',
        image: '../assets/rice.png',
        subCategory: 'Non-veg',
        starRating: 4.8,
        type: 'restaurant',
    },
    {
        id: 6,
        name: 'Mixed Veg Fried Rice',
        price: '129',
        description: 'A vibrant and healthy stir-fried rice dish packed with a colorful mix of fresh vegetables. The rice is seasoned with light spices, allowing the natural flavors of the vegetables to shine through. It’s a nutritious option that’s perfect for a quick and wholesome meal.',
        image: '../assets/rice.png',
        subCategory: 'Veg',
        starRating: 4.1,
        type: 'restaurant',
    },
    {
        id: 7,
        name: 'Hyderabadi Chicken Biryani',
        price: '229',
        description: 'A flavorful and spicy biryani featuring tender chicken cooked with aromatic basmati rice and a blend of traditional spices. The dish is renowned for its rich taste and vibrant colors, making it a favorite among biryani enthusiasts looking for a robust and satisfying meal.',
        image: '../assets/rice.png',
        subCategory: 'Non-veg',
        starRating: 4.7,
        type: 'restaurant',
    },
    {
        id: 8,
        name: 'Vegetable Hakka Noodles',
        price: '119',
        description: 'Delicious stir-fried noodles tossed with a variety of fresh vegetables in a tangy and slightly spicy sauce. This dish combines the crunch of the vegetables with the softness of the noodles, creating a balanced and flavorful meal that’s both satisfying and easy to enjoy.',
        image: '../assets/rice.png',
        subCategory: 'Veg',
        starRating: 3.9,
        type: 'restaurant',
    },
    {
        id: 9,
        name: 'Chicken Schezwan Rice',
        price: '159',
        description: 'A spicy and flavorful rice dish featuring tender pieces of chicken and a blend of vegetables cooked in Schezwan sauce. The bold flavors and slight heat make this dish a delicious option for those who enjoy a bit of spice in their meal.',
        image: '../assets/rice.png',
        subCategory: 'Non-veg',
        starRating: 4.3,
        type: 'restaurant',
    },
    {
        id: 10,
        name: 'Veg Biryani',
        price: '149',
        description: 'Aromatic basmati rice cooked with a blend of fresh vegetables and spices. This dish offers a delightful combination of textures and flavors, with the vegetables adding a satisfying crunch and the spices enhancing the overall taste. It’s a well-balanced and flavorful option for vegetarians.',
        image: '../assets/rice.png',
        subCategory: 'Veg',
        starRating: 4.2,
        type: 'restaurant',
    },
    {
        id: 11,
        name: 'Prawn Fried Rice',
        price: '199',
        description: 'A savory fried rice dish featuring succulent prawns stir-fried with rice and a mix of vegetables. The prawns add a delicious seafood flavor, while the vegetables provide a satisfying crunch. This dish is seasoned to perfection, offering a delightful combination of flavors and textures.',
        image: '../assets/rice.png',
        subCategory: 'Non-veg',
        starRating: 4.6,
        type: 'restaurant',
    },
    {
        id: 12,
        name: 'Veg Manchurian Rice',
        price: '139',
        description: 'Crispy veg Manchurian balls served with flavorful fried rice. The Manchurian balls are coated in a tangy and spicy sauce, perfectly complementing the rice. This dish offers a satisfying combination of crispy and tender textures with a bold flavor profile that’s sure to please.',
        image: '../assets/rice.png',
        subCategory: 'Veg',
        starRating: 4.0,
        type: 'restaurant',
    },
    {
        id: 13,
        name: 'Fish Biryani',
        price: '249',
        description: 'Aromatic basmati rice cooked with tender fish pieces and a blend of spices. This traditional biryani offers a rich and flavorful experience, with the fish adding a unique twist to the classic dish. It’s a great option for those seeking a different take on biryani.',
        image: '../assets/rice.png',
        subCategory: 'Non-veg',
        starRating: 4.4,
        type: 'restaurant',
    },
    {
        id: 14,
        name: 'Jeera Rice',
        price: '99',
        description: 'Simple yet flavorful rice dish infused with the aromatic taste of cumin seeds. The cumin seeds add a subtle, earthy flavor that enhances the rice without overpowering it. This dish pairs well with a variety of curries and is perfect for a light and aromatic meal.',
        image: '../assets/rice.png',
        subCategory: 'Veg',
        starRating: 3.8,
        type: 'restaurant',
    },
    {
        id: 15,
        name: 'Keema Fried Rice',
        price: '179',
        description: 'Minced meat stir-fried with rice and a blend of aromatic spices. This hearty dish combines the rich flavors of the keema with the fluffy rice, offering a satisfying and flavorful meal. It’s a great option for those who enjoy a robust and savory rice dish.',
        image: '../assets/rice.png',
        subCategory: 'Non-veg',
        starRating: 4.5,
        type: 'restaurant',
    },
    {
        id: 16,
        name: 'Veg Schezwan Fried Rice',
        price: '129',
        description: 'Spicy and tangy fried rice mixed with a variety of fresh vegetables. The Schezwan sauce adds a bold and zesty flavor to the rice, while the vegetables provide a crunch and freshness. This dish is perfect for those who enjoy a bit of heat and a lot of flavor.',
        image: '../assets/rice.png',
        subCategory: 'Veg',
        starRating: 4.0,
        type: 'restaurant',
    },
    {
        id: 17,
        name: 'Mushroom Biryani',
        price: '189',
        description: 'Aromatic basmati rice cooked with mushrooms and a blend of spices. The mushrooms add a savory umami flavor, making this biryani a delicious option for vegetarians. The combination of spices and rice creates a rich and flavorful dish that’s both hearty and satisfying.',
        image: '../assets/rice.png',
        subCategory: 'Veg',
        starRating: 4.2,
        type: 'restaurant',
    },
    {
        id: 18,
        name: 'Chicken Tikka Biryani',
        price: '219',
        description: 'Grilled chicken tikka served with spiced basmati rice in a biryani style. The tender chicken pieces are marinated and grilled to perfection, then combined with flavorful rice for a dish that’s both spicy and satisfying. This biryani offers a wonderful blend of grilled and spiced flavors.',
        image: '../assets/rice.png',
        subCategory: 'Non-veg',
        starRating: 4.7,
        type: 'restaurant',
    },
    {
        id: 19,
        name: 'Schezwan Chicken Noodles',
        price: '159',
        description: 'Spicy chicken noodles stir-fried with fresh vegetables and Schezwan sauce. The noodles are cooked to perfection and tossed with tender chicken and a tangy sauce, creating a flavorful and satisfying dish. Ideal for those who enjoy a bit of spice and a lot of flavor in their meal.',
        image: '../assets/rice.png',
        subCategory: 'Non-veg',
        starRating: 4.3,
        type: 'restaurant',
    },
    {
        id: 20,
        name: 'Paneer Fried Rice',
        price: '149',
        description: 'Crispy paneer pieces stir-fried with rice and seasoned with a blend of spices. The paneer adds a creamy texture and rich flavor to the rice, while the spices enhance the overall taste. This dish is a delightful option for those who enjoy a vegetarian rice meal with a touch of spice.',
        image: '../assets/rice.png',
        subCategory: 'Veg',
        starRating: 4.1,
        type: 'restaurant',
    }
];
