export const restaurants = [
    {
        id: 21,
        name: 'Palak Paneer',
        description: 'A classic North Indian dish featuring soft paneer cubes cooked in a smooth spinach gravy. This healthy and flavorful dish is seasoned with aromatic spices and is perfect when paired with roti or rice.',
        image: '../assets/palak-paneer.png',
        subCategory: 'Veg',
        starRating: 4.3,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 219,
                discountedPrice: 199,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 399,
                discountedPrice: 369,
            },
        ],
    },
    {
        id: 22,
        name: 'Tandoori Chicken',
        description: 'A popular Indian dish featuring marinated chicken cooked in a tandoor oven. The smoky flavor, vibrant color, and succulent texture make this dish a must-try for lovers of grilled chicken.',
        image: '../assets/tandoori-chicken.png',
        subCategory: 'Non-Veg',
        starRating: 4.8,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 299,
                discountedPrice: 269,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 549,
                discountedPrice: 499,
            },
        ],
    },
    {
        id: 23,
        name: 'Mushroom Masala',
        description: 'A rich and flavorful dish made with button mushrooms cooked in a spicy onion and tomato gravy. This vegetarian delight is perfect when paired with chapati or rice, offering a balanced blend of flavors and textures.',
        image: '../assets/mushroom-masala.png',
        subCategory: 'Veg',
        starRating: 4.1,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 199,
                discountedPrice: 179,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 349,
                discountedPrice: 319,
            },
        ],
    },
    {
        id: 24,
        name: 'Fish Fry',
        description: 'Crispy and golden-fried fish fillets marinated in a blend of spices. This dish offers a perfect combination of crunch and tenderness, making it a delightful appetizer or side dish.',
        image: '../assets/fish-fry.png',
        subCategory: 'Non-Veg',
        starRating: 4.5,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 249,
                discountedPrice: 229,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 479,
                discountedPrice: 439,
            },
        ],
    },
    {
        id: 25,
        name: 'Chicken Korma',
        description: 'A luxurious and creamy chicken curry made with yogurt, cream, and a blend of spices. This mildly spiced dish is perfect for those who enjoy rich and aromatic flavors, best served with naan or steamed rice.',
        image: '../assets/chicken-korma.png',
        subCategory: 'Non-Veg',
        starRating: 4.7,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 279,
                discountedPrice: 249,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 529,
                discountedPrice: 479,
            },
        ],
    },
    {
        id: 26,
        name: 'Shahi Paneer',
        description: 'A rich and creamy North Indian curry made with paneer cubes cooked in a luscious gravy of cream, yogurt, and aromatic spices. This dish is perfect when paired with naan or paratha, offering a regal and flavorful experience.',
        image: '../assets/shahi-paneer.png',
        subCategory: 'Veg',
        starRating: 4.4,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 239,
                discountedPrice: 209,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 419,
                discountedPrice: 379,
            },
        ],
    },
    {
        id: 27,
        name: 'Prawn Masala',
        description: 'A spicy and tangy curry made with succulent prawns cooked in a blend of aromatic spices and tomatoes. This dish is perfect for seafood lovers who enjoy bold and intense flavors, served best with steamed rice.',
        image: '../assets/prawn-masala.png',
        subCategory: 'Non-Veg',
        starRating: 4.6,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 329,
                discountedPrice: 299,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 629,
                discountedPrice: 579,
            },
        ],
    },
    {
        id: 28,
        name: 'Aloo Paratha',
        description: 'A popular Indian flatbread stuffed with a spicy potato mixture. This comforting and flavorful dish is perfect for breakfast or brunch, served with yogurt or pickle.',
        image: '../assets/aloo-paratha.png',
        subCategory: 'Veg',
        starRating: 4.2,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 149,
                discountedPrice: 129,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 269,
                discountedPrice: 249,
            },
        ],
    },
    {
        id: 29,
        name: 'Paneer Tikka',
        description: 'A popular Indian appetizer featuring marinated paneer cubes grilled to perfection. This dish offers a delightful smoky flavor and is a favorite among vegetarians, served with mint chutney.',
        image: '../assets/paneer-tikka.png',
        subCategory: 'Veg',
        starRating: 4.5,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 239,
                discountedPrice: 209,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 449,
                discountedPrice: 399,
            },
        ],
    },
    {
        id: 30,
        name: 'Chicken Malai Tikka',
        description: 'Tender chicken pieces marinated in a creamy and mildly spiced mixture, grilled to perfection. The creamy texture and subtle flavors make this dish a melt-in-the-mouth experience, served best with green chutney.',
        image: '../assets/chicken-malai-tikka.png',
        subCategory: 'Non-Veg',
        starRating: 4.7,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 299,
                discountedPrice: 269,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 549,
                discountedPrice: 499,
            },
        ],
    },
    {
        id: 31,
        name: 'Palak Paneer',
        description: 'A classic North Indian dish made with tender paneer cubes cooked in a creamy spinach gravy. The rich and mildly spiced flavors make this a comforting and nutritious meal, perfect when paired with naan or steamed rice.',
        image: '../assets/palak-paneer.png',
        subCategory: 'Veg',
        starRating: 4.6,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 229,
                discountedPrice: 209,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 399,
                discountedPrice: 369,
            },
        ],
    },
    {
        id: 32,
        name: 'Mushroom Masala',
        description: 'A flavorful curry featuring tender mushrooms cooked in a rich, spicy gravy made with tomatoes, onions, and aromatic spices. This dish offers a delightful blend of earthy and tangy flavors, ideal for pairing with rice or roti.',
        image: '../assets/mushroom-masala.png',
        subCategory: 'Veg',
        starRating: 4.3,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 209,
                discountedPrice: 189,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 379,
                discountedPrice: 349,
            },
        ],
    },
    {
        id: 33,
        name: 'Chicken Shawarma',
        description: 'Juicy marinated chicken wrapped in soft pita bread with fresh vegetables and a tangy garlic sauce. The combination of tender chicken and vibrant veggies creates a delicious and satisfying meal.',
        image: '../assets/chicken-shawarma.png',
        subCategory: 'Non-Veg',
        starRating: 4.5,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 179,
                discountedPrice: 159,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 299,
                discountedPrice: 269,
            },
        ],
    },
    {
        id: 34,
        name: 'Paneer Tikka',
        description: 'Marinated paneer cubes grilled to perfection, offering a smoky and spiced flavor. This popular starter is served with mint chutney and is loved for its rich taste and appetizing texture.',
        image: '../assets/paneer-tikka.png',
        subCategory: 'Veg',
        starRating: 4.7,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 249,
                discountedPrice: 229,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 449,
                discountedPrice: 419,
            },
        ],
    },
    {
        id: 35,
        name: 'Aloo Paratha',
        description: 'A stuffed Indian flatbread made with seasoned mashed potatoes and spices, cooked until golden and crisp. This comforting and flavorful dish is best enjoyed with yogurt or pickle.',
        image: '../assets/aloo-paratha.png',
        subCategory: 'Veg',
        starRating: 4.2,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Single Paratha',
                price: 129,
                discountedPrice: 109,
            },
            {
                id: 2,
                unit: 'Double Paratha',
                price: 249,
                discountedPrice: 229,
            },
        ],
    },
    {
        id: 36,
        name: 'Fish Tikka',
        description: 'Succulent fish fillets marinated in a blend of spices and yogurt, grilled to perfection. The smoky flavors and tender texture make this dish a must-try for seafood lovers.',
        image: '../assets/fish-tikka.png',
        subCategory: 'Non-Veg',
        starRating: 4.6,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 349,
                discountedPrice: 319,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 599,
                discountedPrice: 559,
            },
        ],
    },
    {
        id: 37,
        name: 'Chicken Korma',
        description: 'A rich and creamy curry made with tender chicken pieces simmered in a blend of aromatic spices and yogurt. This mildly spiced dish is perfect for those who enjoy a flavorful yet gentle curry.',
        image: '../assets/chicken-korma.png',
        subCategory: 'Non-Veg',
        starRating: 4.4,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 299,
                discountedPrice: 269,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 549,
                discountedPrice: 509,
            },
        ],
    },
    {
        id: 38,
        name: 'Paneer Bhurji',
        description: 'Scrambled paneer cooked with onions, tomatoes, and spices, offering a rich and flavorful dish that is perfect for pairing with roti or paratha. This protein-packed dish is a favorite among vegetarians.',
        image: '../assets/paneer-bhurji.png',
        subCategory: 'Veg',
        starRating: 4.3,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 189,
                discountedPrice: 169,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 329,
                discountedPrice: 299,
            },
        ],
    },
    {
        id: 39,
        name: 'Tandoori Chicken',
        description: 'A classic Indian dish featuring marinated chicken roasted in a tandoor oven, resulting in a smoky and flavorful experience. Served with lemon and mint chutney, this dish is a hit among non-veg lovers.',
        image: '../assets/tandoori-chicken.png',
        subCategory: 'Non-Veg',
        starRating: 4.8,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 329,
                discountedPrice: 299,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 599,
                discountedPrice: 549,
            },
        ],
    },
    {
        id: 40,
        name: 'Gobi Manchurian',
        description: 'Crispy cauliflower florets tossed in a tangy and spicy sauce, offering a burst of flavors with every bite. This popular Indo-Chinese dish is loved for its crunchy texture and bold taste.',
        image: '../assets/gobi-manchurian.png',
        subCategory: 'Veg',
        starRating: 4.5,
        type: 'restaurant',
        units: [
            {
                id: 1,
                unit: 'Half Plate',
                price: 169,
                discountedPrice: 149,
            },
            {
                id: 2,
                unit: 'Full Plate',
                price: 319,
                discountedPrice: 289,
            },
        ],
    },


];
